# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameter_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import coordinator_pb2 as coordinator__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16parameter_server.proto\x12\nversoscale\x1a\x11\x63oordinator.proto\"\r\n\x0bPullRequest\"M\n\x0eParameterChunk\x12\x12\n\nlayer_name\x18\x01 \x01(\t\x12\x14\n\x0ctensor_bytes\x18\x02 \x01(\x0c\x12\x11\n\ttenant_id\x18\x03 \x01(\t\"\xab\x01\n\rGradientChunk\x12\x12\n\nlayer_name\x18\x01 \x01(\t\x12>\n\x0b\x63ompression\x18\x02 \x01(\x0e\x32).versoscale.GradientChunk.CompressionType\x12\x14\n\x0ctensor_bytes\x18\x03 \x01(\x0c\"0\n\x0f\x43ompressionType\x12\x08\n\x04NONE\x10\x00\x12\x13\n\x0fQUANTIZED_UINT8\x10\x01\"\x19\n\x07PushAck\x12\x0e\n\x06status\x18\x01 \x01(\t2\xe9\x01\n\x16ParameterServerService\x12G\n\x0ePullParameters\x12\x17.versoscale.PullRequest\x1a\x1a.versoscale.ParameterChunk0\x01\x12\x41\n\rPushGradients\x12\x19.versoscale.GradientChunk\x1a\x13.versoscale.PushAck(\x01\x12\x43\n\x0eSyncParameters\x12\x1a.versoscale.ParameterChunk\x1a\x13.versoscale.SyncAck(\x01\x62\x06proto3')



_PULLREQUEST = DESCRIPTOR.message_types_by_name['PullRequest']
_PARAMETERCHUNK = DESCRIPTOR.message_types_by_name['ParameterChunk']
_GRADIENTCHUNK = DESCRIPTOR.message_types_by_name['GradientChunk']
_PUSHACK = DESCRIPTOR.message_types_by_name['PushAck']
_GRADIENTCHUNK_COMPRESSIONTYPE = _GRADIENTCHUNK.enum_types_by_name['CompressionType']
PullRequest = _reflection.GeneratedProtocolMessageType('PullRequest', (_message.Message,), {
  'DESCRIPTOR' : _PULLREQUEST,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:versoscale.PullRequest)
  })
_sym_db.RegisterMessage(PullRequest)

ParameterChunk = _reflection.GeneratedProtocolMessageType('ParameterChunk', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERCHUNK,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:versoscale.ParameterChunk)
  })
_sym_db.RegisterMessage(ParameterChunk)

GradientChunk = _reflection.GeneratedProtocolMessageType('GradientChunk', (_message.Message,), {
  'DESCRIPTOR' : _GRADIENTCHUNK,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:versoscale.GradientChunk)
  })
_sym_db.RegisterMessage(GradientChunk)

PushAck = _reflection.GeneratedProtocolMessageType('PushAck', (_message.Message,), {
  'DESCRIPTOR' : _PUSHACK,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:versoscale.PushAck)
  })
_sym_db.RegisterMessage(PushAck)

_PARAMETERSERVERSERVICE = DESCRIPTOR.services_by_name['ParameterServerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PULLREQUEST._serialized_start=57
  _PULLREQUEST._serialized_end=70
  _PARAMETERCHUNK._serialized_start=72
  _PARAMETERCHUNK._serialized_end=149
  _GRADIENTCHUNK._serialized_start=152
  _GRADIENTCHUNK._serialized_end=323
  _GRADIENTCHUNK_COMPRESSIONTYPE._serialized_start=275
  _GRADIENTCHUNK_COMPRESSIONTYPE._serialized_end=323
  _PUSHACK._serialized_start=325
  _PUSHACK._serialized_end=350
  _PARAMETERSERVERSERVICE._serialized_start=353
  _PARAMETERSERVERSERVICE._serialized_end=586
# @@protoc_insertion_point(module_scope)
